name: Run JS Scraper

on:
  schedule:
    - cron: '0 * * * *'   # runs every hour
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # or your preferred version

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node scraper.js

      - name: Commit scraped data
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/articles.json
          git commit -m "Update scraped data" || echo "No changes to commit"
          git push
